services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: "cd src && pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "cd src && gunicorn project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:H6sEXwhEgWA6KWFi@db.dwesnrinrszmstvduvue.supabase.co:5432/postgres
      - key: DJANGO_SECRET_KEY
        value: ^2_v=cohj4z*1ef^&#ff^$5y!f)8=kvyvy6#t8@yhpmh-hw_)%
      - key: DEBUG
        value: False
